### PR TITLE
Add support for GHC-9.0.1

### LINKED ISSUE #11: Support GHC-9.0.1
When trying to build on ghc-9.0.1 it fails with this error

```
Building library for ghc-check-0.5.0.2..
[2 of 4] Compiling GHC.Check.Util   ( src/GHC/Check/Util.hs, ... )

src/GHC/Check/Util.hs:10:28: error:
    Module ‘GHC’ does not export ‘gcatch’
   |
10 | import           GHC (Ghc, gcatch)
   |                            ^^^^^^
```

According to the [release notes](https://gitlab.haskell.org/ghc/ghc/-/blob/master/docs/users_guide/9.0.1-notes.rst), `gcatch` is removed and their ``exceptions``-alternatives are meant to be used instead.

### PR DESCRIPTION
**Pull request by anka-213**
Fixes #11

There is a bit of code duplication as a result of CPP pragmas for backwards compatibility that could probably be cleaned up. I hope that it's be fine, it can be cleaned up later if necessary.

Tested (compiled)  on GHC-8.8.4, GHC-8.10.4 and GHC-9.0.1

One more tiny step towards: https://github.com/haskell/haskell-language-server/issues/297

### CODE REVIEW

**Comment by jneira** [comment]
It is only for me or you are able to see hlint warnings from ci in file changes? 😮

**Comment by anka-213** [comment]
Yes, I see them too. Not sure how it works.

**Comment by jneira** [comment]
@pepeiborra do you think it is ready to be merged?

**Comment by pepeiborra** [comment]
Sorry, I missed this. Will review and merge tonight

**Comment by anka-213** [comment]
Ghc complains about non-exhaustive pattern matches here. Is this anything to be concerned about or will the non-covered cases never happen?
https://github.com/pepeiborra/ghc-check/blob/d19d49ad8efcc5f2a07bc5b5c186aa47ca8fec94/src/GHC/Check.hs#L221-L227

I guess this is kind of orthogonal to the pull request. I just noticed it while working on the ghc9 compatibility, since I enabled warnings.

File: src/GHC/Check/PackageDb.hs [hunk 1]
```diff
@@ -45,6 +69,31 @@ data PackageVersion
...
+
+  p <- explicit <|> notExplicit
+
+  return $ fromPackageConfig p
+
+fromPackageConfig :: UnitInfo -> PackageVersion
+fromPackageConfig p = PackageVersion (MyVersion $ unitPackageVersion p) (Just $ unitAbiHash p)
+
+#else
+
```
Comment (anka-213) [inline src/GHC/Check/PackageDb.hs:89]: This code duplication is pretty ugly and I should probably define versions of `lookupUnit`/`lookupPackage` etc. that are compatible with both versions instead. I've done that in the [`Development.IDE.GHC.Compat`](https://github.com/haskell/haskell-language-server/pull/1649/files#diff-a54f7055c79019e6a0bfbac7b8dcce0048de756ad4ea47d02a161177dd57d9ac) module when working on ghc9 compatibility for ghcide.

File: src/GHC/Check/Util.hs [hunk 2]
```diff
@@ -4,13 +4,15 @@
 {-# LANGUAGE CPP, TemplateHaskell #-}
 module GHC.Check.Util (MyVersion(..), liftTyped, gcatchSafe) where
 
-import           Control.Exception.Safe
+import           Control.Exception.Safe as Safe
 import           Control.Monad.IO.Class (MonadIO(liftIO))
 import           Data.Version ( Version, parseVersion )
-import           GHC (Ghc, gcatch)
+import           GHC (Ghc)
```
Comment (anka-213) [inline src/GHC/Check/Util.hs:10]: I'm not sure if I should add CPP pragmas to avoid these warnings

File: src/GHC/Check/Util.hs [hunk 3]
```diff
@@ -4,13 +4,15 @@
...
+import qualified GHC
```
Comment (anka-213) [inline src/GHC/Check/Util.hs:11]: I'm not sure if I should add CPP pragmas to avoid these "Redundant imports" warnings

Comment (jneira) [reply src/GHC/Check/Util.hs:11]: i usually do it to clean up warnings but to make explicit what are we picking for each ghc version

Comment (anka-213) [reply src/GHC/Check/Util.hs:11]: Makes sense

File: src/GHC/Check/PackageDb.hs [hunk 4]
```diff
@@ -15,26 +17,48 @@ where
...
+import GHC.Data.Maybe (MaybeT (MaybeT), runMaybeT)
+-- import GHC.Unit.Module (toUnitId)
+import GHC.Unit.Info (PackageName (PackageName))
+import GHC.Unit.State
+  (lookupUnit, explicitUnits,  lookupUnitId,
+    lookupPackageName
+  )
+import GHC.Unit.State (GenericUnitInfo (..))
+import GHC.Unit.State (UnitInfo)
+import GHC.Unit.State (unitPackageNameString)
```
Comment (pepeiborra) [inline src/GHC/Check/PackageDb.hs]:
```suggestion
import GHC.Unit.State
  (lookupUnit, explicitUnits,  lookupUnitId,
    lookupPackageName, GenericUnitInfo (..), 
    UnitInfo, unitPackageNameString)
```

File: src/GHC/Check/PackageDb.hs [hunk 5]
```diff
@@ -15,26 +17,48 @@ where
...
+import Language.Haskell.TH.Syntax (Lift)
+import Data.Foldable (find)
+import Control.Applicative (Alternative((<|>)))
+#if MIN_VERSION_ghc(9,0,1)
+import GHC
+  (unitState,  Ghc,
+    getSessionDynFlags,
+  )
+import GHC.Data.Maybe (MaybeT (MaybeT), runMaybeT)
+-- import GHC.Unit.Module (toUnitId)
```
Comment (pepeiborra) [inline src/GHC/Check/PackageDb.hs]:
```suggestion
```

File: src/GHC/Check/PackageDb.hs [hunk 6]
```diff
@@ -15,26 +17,48 @@ where
...
+  (lookupUnit, explicitUnits,  lookupUnitId,
+    lookupPackageName
+  )
+import GHC.Unit.State (GenericUnitInfo (..))
+import GHC.Unit.State (UnitInfo)
+import GHC.Unit.State (unitPackageNameString)
+import GHC.Unit.Types (indefUnit)
+-- import GHC.Unit.Types (Unit, UnitId)
+-- import GHC.Driver.Session (DynFlags)
+-- import GHC.Unit.State (UnitState)
```
Comment (pepeiborra) [inline src/GHC/Check/PackageDb.hs]:
```suggestion
```

File: src/GHC/Check/PackageDb.hs (hunk 1 above)
Comment (pepeiborra) [reply src/GHC/Check/PackageDb.hs:89]: That module from ghcide should almost live in a standalone package so that it can be reused elsewhere. But no need to extract it just for ghc-check, I am fine with the duplication for the time being

**Comment by pepeiborra** [comment]
> Ghc complains about non-exhaustive pattern matches here. Is this anything to be concerned about or will the non-covered cases never happen?
> 
> https://github.com/pepeiborra/ghc-check/blob/d19d49ad8efcc5f2a07bc5b5c186aa47ca8fec94/src/GHC/Check.hs#L221-L227
> 
> I guess this is kind of orthogonal to the pull request. I just noticed it while working on the ghc9 compatibility, since I enabled warnings.

The pattern matches are exhaustive since the set of packages used to do ABI checks is hardcoded to "base" and "ghc".

**Comment by pepeiborra** [comment]
Thank you - for the careful 9.0 upgrade and also for the CI improvements.
I have combined some of the import statements and will merge and release to Hackage once CI is done

**Comment by pepeiborra** [comment]
0.5.0.4 is on Hackage with GHC 9 support
