### ISSUE TITLE
Support GHC-9.0.1

### ISSUE THREAD

**Issue by anka-213** [pepeiborra/ghc-check#11]
When trying to build on ghc-9.0.1 it fails with this error

```
Building library for ghc-check-0.5.0.2..
[2 of 4] Compiling GHC.Check.Util   ( src/GHC/Check/Util.hs, ... )

src/GHC/Check/Util.hs:10:28: error:
    Module ‘GHC’ does not export ‘gcatch’
   |
10 | import           GHC (Ghc, gcatch)
   |                            ^^^^^^
```

According to the [release notes](https://gitlab.haskell.org/ghc/ghc/-/blob/master/docs/users_guide/9.0.1-notes.rst), `gcatch` is removed and their ``exceptions``-alternatives are meant to be used instead.

**Comment by anka-213** [comment]
After fixing that issue, there are a bunch of other issues from template Haskell, caused by https://github.com/ghc-proposals/ghc-proposals/pull/195, and from PackageDb caused by https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3237.

I have a fix, but I haven't used CPP pragmas to make it backwards compatible yet.
